// Code generated by tygo. DO NOT EDIT.
import type {HostInfo} from "./sysinfo.ts"
import type {HostMemoryInfo} from "./sysinfo.ts"

//////////
// source: cayman.go

export type Module = any;

//////////
// source: types_dashboard.go

/**
 * HostState is used on the dashboard
 */
export interface HostState {
    hostname: string;
    fqdn: string; // Include FQDN
    load: Load;
    cpu: number /* int */; // Include CPU usage
    cpu_count: number /* int */; // Include CPU count
    unit_status: UnitStatus; // Include unit status
    /**
     * CPUInfo       cpu.InfoStat             `json:"cpu_info"`       // Include CPU info
     */
    physical_cores: number /* int */; // Include physical cores
    logical_cores: number /* int */; // Include logical cores
    host_info: HostInfo; // Include host info
    memory_info: HostMemoryInfo; // Include memory info
}
export interface UnitStatus {
    failed_count: number /* int */;
    active_count: number /* int */; // Include active count
}
export interface Load {
    load1: number /* float64 */;
    load5: number /* float64 */;
    load15: number /* float64 */;
}
